language: python
python:
  - 3.6

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

# Install python dependencies from requirements file
install:
  - pip install -r requirements.txt

# Basic python linting tests
script:
  - pylama .
  - black --check .
